### ISSUE TITLE
Would love to help develop this again

### ISSUE THREAD

**Issue by david-shortman** [jonnylin13/LDN#59]
Wanted to see if this project was still active and contribute, maybe even get Firefox and Safari working, or other streaming services. Otherwise might fork.

**Comment by jonnylin13** [comment]
Sorry @david-mccoy, this project has been inactive for awhile. I'd be glad to give you any pointers to help you along the way!

**Comment by david-shortman** [comment]
Thanks for responding! I'm actually looking into uncovering Netflix Party's API right now, so will be pursuing that instead.
